#+TITLE: DawnStorm
#+AUTHOR: Michal Atlas
#+DESCRIPTION: A 3D6 Pen & Paper RPG

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/readtheorg/css/htmlize.css"/>
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://www.pirilampo.org/styles/readtheorg/css/readtheorg.css"/>

#+HTML_HEAD: <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
#+HTML_HEAD: <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/lib/js/jquery.stickytableheaders.js"></script>
#+HTML_HEAD: <script type="text/javascript" src="https://www.pirilampo.org/styles/readtheorg/js/readtheorg.js"></script>

* DawnStorm - A 3D6 Pen & Paper RPG
** Preword

I started this project with the intention of ending up with a simple RPG
system, that nonetheless felt good and was fast to play. The second goal
was to give as much freedom as possible, while keeping it simple for
both the players and the GM.

When you see something colored like =THIS= it is a keyword and will be
explained somewhere later on.

Some parts are labeled like

#+BEGIN_QUOTE
    THIS
#+END_QUOTE

These provide some additional
suggestions, explanations or just general commentary.

When dividing or multiplying, Always round *against* your favor.

The last thing is that almost all of this is built as suggestions, I'm
more than happy if the players ask politely for items not on lists,
spell words not shown and races not recommended, that is one of the
points to the game.

On that note, many things will be published on this site. Aside from the
core rulebook, you should agree on which of these to use as some may be
game or theme breaking.

This webpage is generated from an org-mode file along with the help of
a theme taken from [[https://github.com/paulzql/org-html-themes][this Repo]], thank you to everyone who creates and shares great things.

I don't think this system infringes any copyright, however I play DrD2, GURPS, DnD 5e and have been reading many others, such as Ars Magica, so some mechanics might end up being very similar or same as some of these, even though I try to stop myself form doing so whenever I notice it.

Now, let's get rolling.

** Skill Checks

When you need to check if you succeeded at a particular task, you roll
3D6 and if you Rolled *higher* or equal to the =Roll Difficulty=
(further called =RD=) you were successfull. Many effects will subtract
or add to your roll, most commonly your Professions. You may add, up to
two Profession's bonuses from your roll.

| RD |        |
|----+--------|
| 8  | Easy   |
| 11 | Normal |
| 13 |        |
| 15 | Hard   |

*Group checks* - If you need to use a skill against a crowd, roll 4
times for the crowd, the whole crowd is divided on the subject based on
the success rate of the rolls.

** Character creation
*** Race
The [[The DawnStorm Bestiary][Bestiary]] contains some suggestions for this.

*** Stats

You have 3 stats in the DawnStorm game, =Body=, =Soul= and =Influence=.
These represent everything you can do, and you should be able to
categorize all actions under one of these stats. Occassionally called
points for ease of wording.

According to the power of your character you start with a number of
points divided between your stats, 15 to 20 is suggested.

| Stat      | Examples                                                                 |
|-----------+--------------------------------------------------------------------------|
| Body      | strength, constitution                                                   |
| Soul      | overcoming horrors and fears, resisting magic and torture, casting magic |
| Influence | persuasion, bartering with shopkeeps, underworld contacts                |

When you are damaged or hurt, you will "lose" these Stats, but only
temporarily, your maximum in the Stat always stays the same. Consider it
similar to losing Hit Points or Mana. For example: damage in combat
loses =Body=, verbal put-downs cost you =Influence=

*Regeneration* - You regenerate 4 stats after 8 hours of sleep, if you
sleep at least 4 hours, you regain 2. Taking other types of long rests
can gain you back 1 stat and wounds can be considered tended to.

#+BEGIN_QUOTE
  Easy Mode - Your stats regenerate after 8 hours of sleep, if you don't manage that amount, you regenerate only half of your total if you slept at least four hours, otherwise one quarter.
#+END_QUOTE

*Scarring* - When you are out of a given stat and some event forces you
to lose it, you must =Scar= yourself, in other situations you may =Scar=
yourself voluntarily. These symbolize damage beyond something you can
walk-of after a day or two. A scar should be accompanied with recieving
an effect, or finding out about one (such as poison). A =Scar= is drawn
across already spent points, and gives you =2 + 2 x Each spent point=.
This wound always has an explanation to what it is and should affect
your character even when outside combat. The taken up points of the Stat
become unusable until you deal with the problem that is connected to the
=Scar=. A =Scar's Rank= is equal to the number of points it makes
unusable. If an effect would grant you additional Points in a Stat, you
cannot Scar these, you may only Scar your own Stats.

| Stat + Scar Rank | Example Wound                     |
|------------------+-----------------------------------|
| Body Rank 1      | Deeper cut                        |
| Body Rank 2      | Major Food Poisoning              |
| Body Rank 3      | Stopped a sword with your Forearm |
| Body Rank 5      | Missing Limb                      |
| Soul Rank 1      | Small mental quirk                |
| Soul Rank 5      | Borderline madness                |
| Influence Rank 1 | Small public humiliation          |
| Influence Rank 2 | Nasty local rumours               |
| Influence Rank 5 | Denounced by ruler                |

#+BEGIN_QUOTE
  Influence Scars may often apply only based on location, similairly to
  Soul Scar's that may be temporarily triggered by something.
#+END_QUOTE

*Death and Unconsciousness* - Many Scars in any stat is enough to make a
character unplayable, not having any more Unscarred Points in a Stat is
taken as the character being dead, crazy or unable to interact with
normal people. After suffering Body Scars of a total equal to or higher
than 3/4 of your Body stat, you fall unconscious.

*Expanding your skills* - Each time you spend =8XP= in professions, you
can increase by one, any of your Stats.

*non-Professional checks* - If you need to check your success in an
action, that doesn't apply to any of your professions, you may roll with
a bonus of your stat divided by 3 rounded down - 1. For the purpose of
making these slightly more specific, each =Body= stat you have or gain,
should be categorized under =Strength= or =Agility=.

*** Professions

Professions give you bonuses to your rolls and special abilities you can
use. They don't necessarily mean that you are your Profession, having a
Rank in Thief doesn't necessarily translate into your character being a
Thief, it only shows that they have a similar set of skills, that your
character could've picked up and used elsewhere. After performing an
adventureous task, you are awarded =XP= by your GM. The amount of =XP=
you need to improve (=Rank Up=) a Profession is =4XP=. And every
=Rank Up= grants you a =+1= Die roll bonus.

Professions are divided into a couple Tiers, usually 3. =Tier I= is
learning and becoming the professions some sort of apprentice or
student, =Tier II= is the actual profession and =Tier III= is a sort of
veteran status.

#+BEGIN_QUOTE
  University Student \rightarrow Engineer \rightarrow Senior Engineer
#+END_QUOTE

After taking 3 levels in a profession you may start Ranking up its next
Tier, alternatively 1.5x the required amount in any related Professions,
this is always the case with professions that do not have a first Tier.

#+BEGIN_QUOTE
  So having 3 Ranks in Magic Acolyte (Tier I) and 1 rank in Hunter (Tier I) would allow you to take Druid (Tier II)
#+END_QUOTE

Some professions will list prerequisites. These prerequisites are listed
under =Rite= in the description of the =Profession=.

*Skills* - The profession will list some things that it includes and
thus gives bonuses for. The Skills listed are examples, each Profession
includes more than is listed and the judgement of each individual action
that comes up should be up to the Players and the GM (if a specific
ability adds something as a skill, it isn't considered as a skill by
default). If an =Ability= states that you now have a skill in something,
act as if the profession lists it in its skills.

*Abilities* - Professions contain Abilities. You gain one of these
abilities every =Rank Up= in that skill. When you see text in [] square
brackets, those are prerequisites.

*Specialties* - If a =Profession= lists =Specialties=, you must choose
one of them (or make up your own if the GM allows) when =Ranking up=,
they perform as absolutely separate Professions. If it is related
enough, but not quite your speciality, you may use half of the die
bonus.

#+BEGIN_QUOTE
  These are most often Knowledge based, where you choose one domain to
  be learned in.
#+END_QUOTE

As DawnStorm is not setting specific, I do not provide any in this
document, there should be some example ones in the modules. Otherwise,
Skills, should be self explanatory when you create your own professions.
And abilities should be something that someone talented may pick-up
after performing that Profession for about a year's time, I.E. A chef
weighing ingredients perfectly in hand, a librarian remembering a long
book index, or an archer shooting multiple arrows if they perhaps did
that for fun.

** Inventory and Items
*** Weapon Classes

Weapons apart from stated bonuses have a type and length (i.e. long
piercing). When describing an animal's attacks, the same rules can be
used. These give you a free maneuver to use while wielding them and have
an effect:

| Basic Weapon Classes |                                                                          |
|----------------------+--------------------------------------------------------------------------|
| Slashing             | Accurate                                                                 |
| Short Slashing       | Feint                                                                    |
| Blunt                | Powerful                                                                 |
| Piercing             | Powerful                                                                 |
| Short                | You can instead attack twice with a =-2= penalty, but not use a maneuver |
| Long                 | Short arms, cannot use maneuvers against you, except for feint           |
| Shield               | Grants two =Defence= maneuvers                                           |

#+BEGIN_QUOTE
  If nothing is stated, assume no maneuver bonus, medium weapon
#+END_QUOTE

*Load* - A character may only comfortably carry a reasonable number of
minor items and up to their =Body= worth of major items. Major items
being, staffs, swords, rations, guns, tents and the like. Every item
carried above this amount gives you a =-2 Body= on skill checks. If the
item is made for a different size than you, it takes up 1 more or less
for every size between you and the item.

*Makeshift* - Weapons you grab on the spot, without changing in any way,
have a limit of 2 Stats of damage. Optimizing them in some way
(sharpening the stick), limits that to 3. In either case, you cannot use
their free maneuvers. To nullify these limitations, you need to succeed
at an appropriate skill check and input adequate amounts of time and
effort. See [[Item Creation][Item Creation]].

*** Item Creation

When determining the difficulty of lingering effects (such as traps or
camouflage) created by players, let them roll upon creation and then use
that as the =DR=. The GM may raise or lower the =DR= of checks by around
3, if there are advantages or disadvantages such as tools, time or bad
lighting.

** Combat
*** Attacks

To determine the outcome of an attack, roll the attack as a skill check.
Afterwards, the defending party has multiple ways to prevent the damage,
most commonly by using the =Defence= maneuver.

When an attack is made, you will lose stats, the amount is how many
times the difference between your rolls, exceeds your =Die Bonus=.

*Pain* - Recieving damage, gives you a =-3= to all offensive rolls and
=-2= on others, until the end of your next turn or next round, whichever
comes first.

*** Initiative

Combat is initiated by an attack, that creature is first in initiative
and has used up its turn delivering this attack.

After which, others go in the following order:

| # | Action         |
|---+----------------|
| 1 | Unarmed        |
| 2 | Short Weapons  |
| 3 | Medium Weapons |
| 4 | Magic          |
| 5 | Other Actions  |
| 6 | Long Weapons   |

After these are exhausted, 1 Round had passed. Each of these actions
take 1 second.

#+BEGIN_QUOTE
  Basically, every round, the GM goes through, asking: Any Unarmed?, Any
  Magic?, etc. This means that you may change your decisions based on
  what previous actions were taken
#+END_QUOTE

The rest is up to the GM or random chance.

If one party had been ambushed, every member of the other is
automatically =Stumbled=. If you wish to save your action for later,
that is possible, for clarity, these should be announced anyway and go
before all others, once they are used. Only one saved action can be
held, it is lost upon your next turn.

*** Zones

To aid with larger battlefields and positioning, DawnStorm uses Zones.
For Example, you may have a chapel, where the fight is divided between
the two wings, the main hall, the altar, etc. Based on the number of
enemies and the type of attacks there are, you may use as few or many as
is practical. For flying creatures, identical zones exist above the
ground ones, where only the flying creatures can go. Unless stated
otherwise you may attack anyone in your zone.

*** Maneuvers

To use a =Basic= maneuver, you spend 1 Stat, though only if an effect
allows you to use it. =Advanced= maneuvers, marked =A=, cost 2 Stats.

One =Defence/Parry= per turn is free per weapon or shield with which you
didn't attack.

*A - Precise* - Roll 5D6 take lowest 3

*Accurate* - Roll 4d6 take lowest 3

*A - Mighty* - Causes target to lose double from a Stat (round down;
minimum 2)

*Powerful* - Causes target to lose =1/2= more from a Stat (round down;
minimum 1)

*Weak* - Causes target to lose half as much of a Stat

*Feint* - You give an ally a free Basic Maneuver against the same enemy
or Kick the creature back attempting to make them stumbled or moving
them; Under 1m and not stumbled if the degree of success is lower than 2

*Defence/Armor/Parry/Dodge* - You roll against the enemy's attack roll +
your rank in this, if you succeed, the hit is absorbed or parried and is
counted as a miss, doesn't work against magical effects by default,
except Dodge

*** Turn Actions

In a turn, you have two phases, a move and a move/action phase. Your
move allows you to move by 1 zone.

As an action you may do one of the following:

- Attack
- Defend - Gain or grant an ally in the same zone =Dodge 0= until the
  start of your next turn
- Activate a Magic Glyph
- Aid - You may roll a skill check against =RD 10=, if you succeed, an
  ally attempting the same check acts as if they are =Skilled=, if both
  of you are skilled, you may roll against =RD 8= , in which case the
  ally rolls as a =Master=
- Ready - Spend the round changing held items, if they're in a bag, you
  should spend 2 actions taking them out. Similair to clothing, putting
  on chainmail would cost a turn, a full suit would cost 2 to 3.
- Perform Action - Such as, put out fire or pull lever

** Environmental Effects

*Fall* - 1 Body per 5 m

*Suffocation* - 1 + your Constitution =Die Bonus= in minutes, then
=Out of Breath= for half a minute, then you are =Exhausted= for 18
seconds, after which you start recieving a growing scar which grows by
one for every 3 seconds. If you are attacked and have to defend in a
physically demanding way (dodging counts, armor does not), you lose 9
seconds of air.

*Food and Water* - not eating or drinking a day gives you -1 to body
based rolls, not recieving sustenance for 3 days, gives you
=Exhaustion=, which increases by 1 level for every day after that.

*Sleep* - not sleeping works the same as food and water, but starts
giving you debuffs after 2 days of no sleep

*Light* - -2 to sight based activities in dim light, -3 in near dark

*Elemental Damage* - You lose 1 body per round of exposure per strength
of element, regular fire causes 1 Body of damage every 2 rounds

** Size

| Size     | Description                         |
|----------+-------------------------------------|
| Scrawny  | Think flies or insects              |
| Tiny     | Smaller than 0.3m in all dimensions |
| Small    | Smaller than 1m in all dimensions   |
| Normal   | Humans                              |
| Large    | From 2m                             |
| Huge     | Bigger than about 5m                |
| Giant    | Dragons                             |
| Colossal | Leviathans, Ancient Dragons         |
| Immense  | Towering over land itself           |
| Primal   | Deities & Titans                    |

If a creature exceeds another's size, it can freely use the =Powerful=
maneuver with Body based encounters against that creature, however the
target acts as if it was =Skilled= at =Dodging= them. Normal has an
average of =5 Body=, going lower subtracts 1, bigger sizes are about 150% of
the previous size.

** Keywords

*Area* - This shows that an action performed affects a certain area such
as an explosion or cannonball. Normally this is specified as a simple
length that specifies the diameter of a sphere or length of a line based
on context.

*RD* - The difficulty of a roll

*Degrees of success* - The number by which you exceed the required =RD=

*Range* - Range is self-explanatory, however it may specify an =I= before the distance to indicate an
incorporeal effect that passes unhindered through solid objects.

*Regeneration* - The creature regains X Body at the start of its turn.
Or every X turns if the value is a fraction (I.E. if x is 1/6 then every 6th turn).

*Natural Armor/Mindlock/Beloved* - Expending the =Body/Soul/Influence=
resource is always reduced by said amount. May specify a source in
parentheses that nullifies this protection.

*Fly* - Describes Fly Speed

*Sense* - Always knows about all movement within a certain radius. It
can feel generally what kind of creature it is.

*Skilled* - Your allowed Base maneuvers are free

*Master* - You may use =Advanced= maneuvers, if you are a =Master= you
are also =Skilled=

*Nightvision* - Does not suffer from lack of proper lighting.

*Recharge* - You roll a D6 and if it's less than X the ability is ready
to use again.

*Immunity* - The stated source cannot cause the creature to expend
Stats.

*Resistance* - Halve the number of Stats lost due to an effect caused by
this source.

*Vulnerability* - Double the number of Stats lost due to an effect
caused by this source.

*Stumped/Distracted* - You can't use any maneuvers, that you choose to
use (that means maneuvers that you spend Stats for or effects that state
you /may/ use them)

*** Conditions

*Stumbled* - you go at the end of initiative (in the order they were
stumbled, if there is more than one) and cannot move more than 1 step,
if you are already stumbled, you lose your next turn. This condition
ends on you turn.

*Short of Breath* - While you are short of breath, you can't use any
=Maneuvers= with your actions that use the =Body= skill, no speech-based
actions and no /Advanced Maneuvers/ with actions using the =Soul= skill.
If you fail an action you become /Exhausted/ for the rest of the
duration + /1 Round/ or just /1 Round/ if the =Out of Breath='s duration
is longer than an hour.

*Exhausted* - You suffer a =-2= on all rolls per level of Exhaustion as
well as all the hindrances given by =Short of Breath=.

*Restrained* -

** Enemies

For ease of play, enemies do not track most of their stats as closely as
players do. They will usually just state =Body=, =Soul= and =Influence=;
or a universal resource called =Fate= if the enemy is fodder enough.
They may state several abilities with cooldowns and attacks with their
own die bonuses. If it is stated that a weapon either carried or
natural, is of a certain type, consider the enemy to be able to use the
maneuvers that those weapons would grant.

Legendary creatures, that are fought mostly 1 against the entire party,
should use Legendary actions. This allows the creature to take an action
after every other creature, as long as it has additional logical ways to
do this. I.E.: Claws, a tail and a fiery breath

* The DawnStorm Bestiary

** Recommended Playable Humanoids

*** Human

Nothing special, the perfect blank slate.

*** Goblin

Size: =Small=

*** Keinfolk

*Kein Roar* - Once a day, you are able to Roar so loud that any
creatures within a 30 meter radius, must succeed at an =RD 9= Check, or
become =Frightened= of you for 6 Seconds.

Incredibly proud, stubborn and loyal creatures, described mostly as
humanoid lions. Pride upon pride, their mane is what defines their
class, long and wavy manes always giving an advantage when arriving in
any Keinfolk society.

*** Talach

*Talach talent* - You are a =Master= at one form of art and =Skilled= in
another.

Tall, with pointed ears, humble and noble, truly a beloved race by most
anyone who meets them. Their curiosity and fantasy had made them into
popular artists and poets, outside their cities often kept in castles
and manors by nobility due to this affinity. Their intelligence hasn't
been perceived to be high nor their strength, manual dexterity is the
one thing they have and which no other race may rival them in.

*** Talkin

*Talkin Ear* - Your ears are very sensitive to whispers and murmurs.
When listening to someone in a crowded room, you hear as if the room was
silent.

They are very similar to the Talach, however their ears are
significantly flatter, lower, sometimes almost horizontal. Quite sly,
sneaky and adept at close range combat, they make excellent spies and
thieves and are often employed as such.

** Beasts
*** Warthorg
** Celestials
*** Angel
** Demons
*** Bone Demons

The bone demons are the knights of the nine hells, they are sent to
retrieve souls that are expected to pose ressistance. They stand about 2
metres tall, carry a great-shield and a slightly curved broadsword or
lance, as well as two daggers lodged into a cavity in their hips. Their
outer appearance is that of a knight, whose plate armour has a surface
similair to a bones. It's head has a fleshy mouth, and then a split into
two flat protrusions to each side. If the bone demon's plates should
come apart you may see that the inside is actually mostly empty, and
held together by occassional oozing strands, the only physical part
being the mouth.

*** Dreadlords
*** Nightcrawler

These dog-like creatures are mostly used by other demons for spying,
hunting and disposing of targets. Their visage is quite simple, the
front half is that of a wolf up until their back legs and hips, which
are just black smoke and non-visible. Their eyes reflect light in
anything but the darkest of places, the light changes color based on the
demon it is currently serving. If a mortal ever manages to calm and tame
a nightcrawler, the smoke coming from its back changes to bright blue
and it becomes apparent that their non-feral nature is quite playful.

*Blinking* They can teleport between two points connected by near pitch
darkness while neither is being observed.

*** Oni
** Fey
*** Changelings

Changelings are the infiltrators of the Fey, they can change their body
to the visage of any humanoid they see at least indirectly. They are
born by imbuing an unborn child with Fey magic. The family usually
doesn't know about this, until the Fey visit the child at 18 years old,
informing it of its destiny. This arduous process is mostly so that the
Changeling blends in as well as possible with other creatures. When a
changeling dies, it reverts to its original form.

*** Dryad

*** Fey Lord

*** Fey Queen

*** Krypsaker

A fey being of intense resilience, it resembles a humanoid, but it seems
as to be disfigured into a goblin-like form, with sharp teeth and
pointed uneven ears and nails. At any point it can turn parts of itself
into insects or birds and Even a single one of these may with enough
nourishment create a whole Krypsaker once more.

*** Pan / Pixie

The most common of the Fey, often incorrectly called forest nymphs, Pans
and their female counterparts called Pixies inhabit kingdoms in many
forests of the world. Their philosophy of life is inherently pacifistic,
created by the titan gaya to protect the forests, the damage of which is
the only way to aggravate them.

They carry human chests and heads, usually with antlers and animal eyes
and ears. Their legs bend backwards above the knee bending backwards
before heading to the ground once more and ending in hooves. Most of
their bodies are covered and seem to be made of leaves, branches and
vines, same as their tools and homes. Being gaya's chosen all wildlife
listens and bends to the needs of the pan.

**** Shadow Pan

**** Hag

** Ghosts

*** Animated Armour

*** Genius Loci

These peculiar demi-ghosts usually manifest in places of great
historical or natural significance that have nonetheless been left to
their own devices. These creatures are usually very shy and rarely ever
speak unless somehow directly invoked. They have been shown to have
knowledge on all matters occurring in their place of existence. These
plains of land where they exist may range from a single ruin to most of
a forest. They communicate telepathically with any sentient creatures
within their domain, however to do this they must concentrate and so
they loose sight of their surroundings for the time being. A very
powerful Genius Loci was once recorded to speak audibly directly through
a human, both of whom shortly lost consciousness afterwards, however
this is only hearsay.

*** Rage

*** Spectra

*** Wendigo

*** Will-o'-Wisp

*** Demi-Ghosts

**** Lost Soul

Lost Souls is a general term for souls that have been prevented from
leaving the world, usually through trapping them inside a container,
very commonly glass spheres or stones. When touching the container one
may telepathically communicate with the soul trapped within. It is said
that the feeling of being a lost soul is like being restrained and
gagged, however you see everything that goes on around you. If left
alone for long enough the soul usually goes crazy within a few weeks,
thus they always wish to be released and will trade next to any help
they can provide for you letting them go. Cracking or opening a
container of the soul, releases it.

*Magic* Lost souls are often used by spellcasters, because the mana of
the original creature still resides within their soul. The soul however,
cannot regenerate mana without the body and so is one use only. /Note/
Please break your soul stones after use.

**** Mirra

Mirras are perfect copies of a creature's conciousness from a certain
point. They are created via a spell etched into the wooden part of a
mirror, binding a present creature to the object, which then shows in
its reflection the bound creature's reflection. The reflection moves
around the room and can talk and recall all the memories of the original
creature, its maneurism and personality are also the same. The Mirra
cannot create new memories or create new impressions on people, it is
always just a perfect copy, however it may utilize very short term
memory or connect concepts to changes in the room which it may ask you
to make. The Mirra recalls existing memories perfectly and
instantaneously.

** Magical Beasts
*** Chimera
*** Griffin
*** Lycanthropes
*** Night-mare
*** Unicorn
** Titans
*** Aegir
*** Atlas
*** Cronus
*** Gaya
*** Prometheus
*** Sekhmet
*** Leviathans
** Plants
** Reptiles
*** Basilisk

A Basilisk is a solitary eight legged reptile-like creature. At first it
walks on all eight, later in life however, when its body is strong
enough to support this development, it's head and front limbs move
upwards and elongate, eventually creating an upright upper body.

*Growth Cycle* The most magnificent property of the Basilisk is its
growth cycle. A Basilisk gives birth to a live baby no larger than a few
inches. The Basilisk then grows inexplicably rapidly as the Basilisk
consumes massive amount of sustenance. At the size of about triple that
of a human the Basilisk develops an upright upper body and loses much of
the potency of its breath. When it reaches such a size that its legs are
struggling to support the body, it migrates to a large body of water.
Even if it hunts enough food, which is rarely the case, its size forces
it to continuously move to ever deeper water, eventually crushing it.

*Breath* The legends often speak of the Basilisk's noxious breath. It
has been observed to have the ability to wither small plants and to
accelerate corrosion of metal. Any effects beyond this are empty claims.

*Gaze* ...

*** Dragon

Every dragons has the ability to transform into a humanoid.

*** Wyvern

Wyverns are very feral animals, true beasts fully devoted to that state
of behaviour. None have ever been recorded to reason or speak unlike
dragons, this is very important to know for any adventurer that may by
any chance encounter this menace. The distinguishing feature is that it
has only four limbs, two legs and two wings, and is inherently
non-magical. At the end of each wing it has claws that it may use to
clamber up surfaces. They come in many forms and colors, though most
often seen in the black form, which is also the most adept at climbing.
Unlike dragons, most Wyverns do not possess a fiery breath, only the red
kind is famously capable of this feat.

*Eggs* Their eggs grow in size as the Wyvern inside matures, being laid
at about half their final size. For this reason the surface is much
softer than one would at first assume, and if even the softness of the
shell is not enough the egg may crack at regular intervals exposing the
inner membrane.

*Weaknesses* You may be tempted to slash the underside of the head,
however unlike dragons, Wyverns have solid armour covering the entire
head. The two weakest points are their thigh joints and the point where
their patagia connect to the body as it has been discovered to easily
tear in the first section. When the wings are folded however the patagia
is relaxed, elastic and quite difficult to pierce without an
exceptionally sharp weapon.

**** Sgrechian

This breed of Wyverns is extremely rare. Usually artificially enchanted
for combat purposes. They naturally have two main characteristics, their
speed, and their scream. Though lacking a beath, they are able to
surpass the sound barrier, by a tiny amount. Their head is often
enchanted with a spell that protects them from impact, it activates with
their scream. Their scream can be heard miles around and has deafened
many who were too close, it is described as being extremely
high-pitched, yet still powerful enough to be felt deep in the guts.

** Undead

*** Ghoul

*** Mummies
**** Haugbui

*** Vampire

*** Zombie

* Module: Eastern
** Professions
*** Kineticist

For every Tier in this class, you add 2 hands to your arsenal. These
hands are ethereal and while not in use, the hands cannot be seen
without magical means. Each hand can carry up to 8 times 2 to the power
of your Tier kilograms. It cannot be separated more than 1 meter from
you and may become incorporeal at will. You may not be able to
concentrate on full control of this form, for every Soul Stat you can
control one hand, or your own two hands in your turn.

* Module: Magic

** Spells

When casting a spell you declare, a Motion and optionally an Element you
know (collectively called words of power), and what the desired outcome
is. Not all elements are useful with all motions.

If your character recieved damage in the last round, you get a
cumulative =-2= to spell =RD= for every =Stat= you lost. Having
restrained hands adds a =-4= to the spell =RD=.

Having plenty of time to draw a magic glyph Reduces the difficulty and
cost of the spell, both by 1 per 10 minutes, but up to your die roll
modifier for spellcasting.

** Magic Glyphs

A magic glyph is created by inscribing a Motion and an Element, with a
very specific intention into a solid surface and empowering them with a
=Soul= or =Soul Fragment=. Mechanically, this requires you to
succesfully cast the spell, and either lower your maximum =Mana= until
it's destroyed or empty a =Soul Stone= into it. Your maximum =Mana=
returns to you after the destruction of the item or the use of a one use
item. If you used your own =Soul Fragment=, the item recharges when your
=Mana= refreshes.

It takes =1 second= per =1 Mana= to create a glyph. If the item is
created with a soul from a =Soul Stone=, it is recharged by draining
mana into the item at a rate of =1 Mana= per second (this mana is
normally spent as if casting a spell). At Dawn and Dusk, a glyph is
sealed and cannot be expanded, only recharged.

Spending additional time and resources during casting (activation),
makes the casting cheaper and easier. Reducing the cost by =1 Mana= and
decreasing the =DR= by 1, costs =10 Silver= of magical materials and
=10 Minutes= times 3 to the power of the amount reduced.

When activated, the glyph casts the spell, draining from the enclosed
mana pool. If the creature that activates a glyph is a magic user with a
=Character=, the spell is cast with that character. You may also
designate a sound or simple occurence (such as someone stepping on it)
that activates the glyph automatically.

#+BEGIN_QUOTE
  Since speech doesn't take up an action, this allows you to activate
  glyphs outside you turn.
#+END_QUOTE

*Soul Stone* - You may substitute a Fragment of your own Soul for a Soul
from a Soul Stone. This allows you to create a glyph without lowering
your own maximum =Mana=, but limits the =Mana= capacity to that of the
Soul used. Soul Stones are quite rare, and have a limited capacity,
however they are reusable.

*Scrolls* - Scrolls produce a one-time Spell effect, they don't require
a =skill check= but still cost mana. Afterwards, the papyrus
disintegrates. Creating one takes 10 minutes per Tier and requires you
to succesfully cast the spell per the Magic Glyph rules.

*Analyzing Magic* - Perceiving a magic glyph, even an instantaneous one
let's you identify any word of power that you know. Identifying those
you don't know, requires a knowledge (arcane) check and some time and
concentration with the glyph or a page of notes you made about it.
Learning a word of power requires several days, of study and
experimentation with notes from several glyphs, with a =RD= of the
number of different notes you're analyzing that have a word in them that
you know.

*Enchanting Items* - Items are Enchanted with tiny magic-glyphs that
require about double time and complete concentration. When a magic-glyph
is on an item that can be entirely lifted by you single-handedly, it can
be activated while touching any point of the item.

*Countering Spells* - You may =Dispel= a non-magic-glyph spell as a
=Defence= maneuver or an =Action=. Dispelling takes half the =Mana= of
the spell and a roll of =RD= of the spell =+3= or =+1= if you know the
motion.

** Spellcasting

Spell-casters can create these glyphs in mid-air instantaneously,
however these persist only for a single round. Long-term effects need an
inscription on a surface to work.

*Mana* - Most effects will ask you to spend mana, you have a basic pool
equal to your =Soul=. At any time you may scar a =Soul= stat to reset
your mana back to that number (this does not let you spend more than
your maximum mana on one spell).

*** Motions

Motions all have multiple Tiers with an =RD= and a =Mana= cost. When
casting a spell with the given motion's tier, you first deduct that much
=Mana= from your pool, then roll against that =RD= to determine if the
spell was successful.

Failing the spell doesn't immediately mean nothing happened, your
=degree of failure= determine that:

| Degree of failure | Effect                                                      |
|-------------------+-------------------------------------------------------------|
| 1-2               | Slightly altered effect if possible, otherwise Failed spell |
| 3-6               | Failed Spell                                                |
| 7+                | The spell backfires, GMs decision                           |

Tier Guidelines:

- *Tier I [=RD10=, =1Mana=]*: Achievable within the hour with sufficient
  skill and tools, the effect vanishes within 10 minutes
- *Tier II [=RD14=, =5Mana=]*: Apparently magical effects, mostly on
  inanimate objects or a small group of about 3 to 5 beings, or advanced
  effects such as manipulation on one person
- *Tier III [=RD20=, =XMana=]*: Complex effects, extending to
  supernatural, manipulating reality with portals and short-range
  teleportation
- *Tier IV [=RD22=, =XMana + Soul Scar=]*:
- *Tier V [=RD24=, =Soul Scar=]*: Miracles

Motions:

- Cease

  - *Tier I*: Stop the movement of an unattended object up to the size
    of a travelling cart
  - *Tier II*: Cease the movement of an object or cease the existence of
    an unattended object up to the size of a travelling cart

- Command

  - *Tier I*: Compel a calm animal to perform some action

- Create

  - *Tier I*: Spontaneously create an item no bigger than the width of
    your hand, creatable from resources that you are touching.
  - *Tier II*: The item, must not exceed your outstretched arms length
    in any dimension.

- Destroy
- Divide/Dislocate

  - *Tier I*: Cut with your finger an inanimate object as if it were a
    knife.
  - *Tier IV*: Cut Metaphysical concepts

- Heal

  - *Tier I*: Close an actively bleeding wound and prevent it from
    getting infected.

- Join

  - *Tier I*: Connect two items that touch in any way and make them
    movable only by a living creature.

- Kill

  - *Tier I*: Cause Rot and Decay in a deceased animal or plant, making
    its body turn to dust within an hour.

- Scry
- Show
- Stride
- Summon
- Transmute

*** Elements

If the spell doesn't contain a corresponding Element for the effect, you
are limited to =Tier I= and =II= spells. Some Elements will contain an
=RD= modifier.

Elements:

- Body
- Cold / Ice
- Earth
- Fire / Heat
- Metal
- Mind
- Nature
- Necros (Necromantic)
- Spectra (Supernatural)
- Time
- Water

*** Characters

These both limit and flavour the spell's effects.

*Draconic* - The spell's effect is exhaled as a cone-shaped breath from
the mouth

*Fey* - All effects are performed by nearby plants

*HexBlade* - The magic is limited only to the wearer himself and mainly
his weapon and armour

*Artistic* - The effects must all be based on art, animate and move
small objects, or create illusions

*Shadow* -

** Miracles

Outside these boundaries lies Divine magic. Monks and priests, worship
and directly invoke a magical being. Others must use complex rituals to
win their interest. Divine magic cannot be understood by non-divine
casters at all. In gameplay the divine spellcaster asks for help from
his deity, in this case the GM is the one who plays the role of god, and
they may do whatever they deem fit in reaction to the character's plea.

** Professions

*** Acolyte

The Acolyte is the basic magic class. Identifying arcane occurences that
you have already seen or know about is the domain of the acolyte.

Skills:

- Spellcasting
- Identifying basic spells and magical effects

Abilities:

- *Amulet user*: You are able to extract Mana from magic glyphs, 1 Mana
  per Second
- *Battle Caster*: You get =+1= per attack (the limit is still =+3=)
  when casting after having taken damage
- *Beast Knowledge*: You have a skill in identifying Magical Beasts
- *Mana Share*: You are able to give your Mana to anyone you touch, 1
  Mana per Second
- *Spellcraft*: You learn 1 Motion and 2 Elements (You may gain a Magic
  Character if your GM allows)
- *Spellcraft 2* [Spellcraft]: You learn an additional 1 Motion/Element
  and 1 Element
- *Spellcraft 3* [Spellcraft 2]: You learn an additional Element

**** Tier II - Mage

Skills:

- *Arcane Memory*: You are able to completely remember up to two magic
  glyphs you've seen at least momentarily
- *Convenient Magic*: You may cast spells with up to 5 Mana without
  spending any
- *Mindlink*:

*** Warmage [4 - Mage + Squire]
Abilities:

- *Sieger*:
- *Incorporeal spells*:
- *Ward*: You have a magical protective ward, which grants you a
  =Defence= maneuver

* Module: Ritual Magic
** Potions
** Professions
*** Druid [Acolyte + Hunter]
*** Vedmak [Hunter + Acolyte]
You hunt magical beasts

Abilities:

- *Beast Form*: By touching a part of a dead magical beast, you may
  assume its form. You gain all its abilities and its Body Stat, however
  when you turn back, all Scars and spent Stats are applied to you. If
  this would kill you, you fall unconscious instead.
- *Beast's wine*: You have =Resistance= against blood based poisons

*** Witch [4 - Acolyte + Herbalist]
* Module: Medieval
** Professions
*** Fighter
Brawls, bar fights and ambushes, you've seen it all. You know what to do
with most common weapons and even better with hands and chairs.

Skills:

- Unarmed Combat
- Combat with short and medium weapons
- Battling with improvised weapons

Abilities:

- *Barbaric Strength*:
- *Brawler*: Your fists are short blunt weapons
- *Dungeoneering*:
- *Hard Skin*: Your skin has =Natural Armor 1= against blunt weapons
- *Rage*:
- *Weapon Improvisation*: Your makeshift weapons grant you the standard
  weapon maneuvers

**** Nord
Skills:

- 

*** Recruit
**** Tier II - Squire

Squires are warriors, who are trained and educated.

Skills:

- Shields
- Long Weapons
- Knowledge - Tactics, Armies, War Codes

Abilities:

- *Field Smith*: You have a skill in repairing damaged armour and
  weapons in the field
- *Footwork*: You are =Skilled= at withstanding movement and stumbling
  by =Feint=
- *Guardian*: You may use your own =Defend= maneuvers on friends
  standing within arms-reach
- *Brothers in Arms*: You may pay with you resources for damaged friends
  standing in arms-reach, if you are able to use the =Defend= maneuver
- *Party Tactics*:
- *Shield Bash*: You are =Skilled= at moving creatures with =Feint=
  using your shield

*** Hunter

Skills:

- Bows or Crossbows (Speciality)
- Tracking
- Knowledge - Animals

Abilities:

- *Always ready*: You have a skill to detect forest ambushes, which you
  may roll even if you are sleeping at =+2=
- *Animal Handling*: Animals are instinctively calmed by your approach,
  unless actively hunting, preparing to fight or fighting
- *Birdsense*: If something frightens away birds that you can hear or
  see, you know it's position and size
- *Bow Slash*: You may modify your bow to have a =+2= on ranged attack
  rolls, however it acts as a =Medium Slashing= weapon
- *Camouflage*: 2 minutes of scavenging in a forest creates camouflage
  for 2 cubic metres
- *Double-shot*: Your skill allows you to load multiple arrows into your
  ranged weapon; You may now use =Powerful= when shooting your weapon of
  choice
- *Traps*: Trap Knowledge and Trapsetting is added to the Skills; You
  may take 10 minutes setting up a trap
- *Urban Tracking*: You are able to use your wilderness tracking skill
  to some limited extent in urban environments

*** Herbalist

Skills:

- Identifying plants and potions
- First-aid and medicine

Abilities:

- *Antidote*: You are able to take up =10 Silver= worth of resources
  after a day of study, to create an antidote to any non-magical disease
- *Artery Strike*: You may forfeit all maneuvers in an attack, after
  which a succesful hit will cause a bleeding wound, costing the carrier
  =1 Body= each round
- *Hidden Poison*: You may attempt to hide your poison from smell and
  taste
- *First-Aid*: After 10 minutes of tending to wounds, give someone back
  2 Stats, up to 4 per day

**** Tier II - Alchemist
*** Noble
You know how to get your way, you know the ins and outs of your society
and you are never out of place amongst the upper-class

Skills:

- Savoire-faire
- High-class speech
- High-class manners

Abilities:

- *Connoseur* - Choose a subject, you are able to talk hours on the
  matters of said subject, be it weapons, literature or wine.

*** Thief

Skills:

- Acrobacy
- Sleight of Hand
- Stealth
- Knowledge - Underground

Abilities:

- *Acrobat*: You are =Skilled= at acrobacy and may use =Precise=
- *Always ready*: You have a skill to detect urban ambushes
- *Cyphers*: Decoding and creating cyphers is now your skill; In
  addition, you know an underground slang
- *Dagger Parry*: You can parry with a dagger even after using it for an
  attack
- *Dual Wielding*:
- *Impersonator*: You have a skill for impersonating other people, a day
  of mentoring allows another person to use your roll
- *Underground Connection*: You know a guy
- *Urban Tracking*: You have a skill for finding out the general
  location of any notable character

** Items, Money and Prices

| Coin            | Worth                        |
|-----------------+------------------------------|
| Copper Penny    | 6 in a commoner's day's work |
| Silver Shilling | 100 Copper Pennies           |
| Platinum        | 5000 Copper Pennies          |
| Gold            | 10000 Copper Pennies         |

| Food           | Price    |
|----------------+----------|
| Day of Rations | 1 Copper |

| Tools | Price |
|-------+-------|
|       |       |

| Weapons   | Price |
|-----------+-------|
| Sword     |       |
| LongSword |       |

| Estates | Price |
|---------+-------|
|         |       |
